uploading of album wrapper (no photos yet) and some little fixes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -25,9 +25,20 @@ fi
 echo "Checking presence of ExifTool..."
 check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*libimage-exiftool-perl[ \t][ \t]*"`
 if [ -z "$check" ]; then
-  echo "Please, install ExifTool library in order to use this program:"
+  echo "Please, install ExifTool in order to use this program:"
   echo "sudo apt-get install libimage-exiftool-perl"
   sudo apt-get install libimage-exiftool-perl
+  if [ $? -ne 0 ]; then echo 'FAIL'; fi
+else
+  echo "OK"
+fi
+
+echo "Checking presence of ImageMagick..."
+check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*imagemagick[ \t][ \t]*"`
+if [ -z "$check" ]; then
+  echo "Please, install ImageMagick in order to use this program:"
+  echo "sudo apt-get install imagemagick"
+  sudo apt-get install imagemagick
   if [ $? -ne 0 ]; then echo 'FAIL'; fi
 else
   echo "OK"
